name: Continuous Integration

on: [push]

jobs:
  java:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.4
      - name: Gradle build
        working-directory: java
        run: ./gradlew build --scan
        env:
          CI: true

  javascript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: NPM install
        working-directory: javascript
        run: |
          npm install
      - name: Unit test
        working-directory: javascript
        run: |
          npm test
        env:
          CI: true
  python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        working-directory: python
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Unit test
        working-directory: python/main
        run: |
          python -m pytest ../tests
        env:
          CI: true

  groovy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.4
      - name: Gradle build
        working-directory: groovy
        run: ./gradlew build --scan
        env:
          CI: true

