name: Clojure

on:
  push:
    paths:
      - 'clojure/**'
      - .github/workflows/clojure.yml

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.4
      - name: Lein test
        working-directory: clojure
        run: lein test
        env:
          CI: true


