name: Javascript

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: NPM install
        working-directory: javascript
        run: |
          npm ci
      - name: Unit test
        working-directory: javascript
        run: |
          npm test
        env:
          CI: true
