name: Python

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install dependencies
        working-directory: python
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Unit test
        working-directory: python/tests
        run: |
          export PYTHONPATH=$PYTHONPATH:../main
          python3 -m pytest -vv
        env:
          CI: true
