name: Python

on:
  push:
    paths:
      - 'python/**'
      - .github/workflows/python.yml

jobs:

  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: 'pip'

      - name: Install dependencies
        working-directory: python
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Unit test
        working-directory: python/tests
        run: |
          export PYTHONPATH=$PYTHONPATH:../main
          python3 -m pytest -vv
        env:
          CI: true
